### ISSUE TITLE
xcollector dies with 'Bad Status'

### ISSUE THREAD

**Issue by talonx** [ApptuitAI/xcollector#24]
```
2018-01-25 14:40:51,330 xcollector[2535] DEBUG: reading ifstat.py, buffer now 1056 bytes
2018-01-25 14:40:52,332 xcollector[2535] DEBUG: reading netstat.py, buffer now 2648 bytes
2018-01-25 14:40:56,371 xcollector[2535] DEBUG: Sending metrics to https://api.apptuit.ai:443/api/put?details
2018-01-25 14:40:59,342 xcollector[2535] DEBUG: reading procstats.py, buffer now 8446 bytes
2018-01-25 14:41:06,353 xcollector[2535] DEBUG: reading ifstat.py, buffer now 1056 bytes
2018-01-25 14:41:07,355 xcollector[2535] DEBUG: reading netstat.py, buffer now 2648 bytes
2018-01-25 14:41:14,364 xcollector[2535] DEBUG: reading procstats.py, buffer now 8446 bytes
2018-01-25 14:41:21,374 xcollector[2535] DEBUG: reading ifstat.py, buffer now 1056 bytes
2018-01-25 14:41:22,375 xcollector[2535] DEBUG: reading netstat.py, buffer now 2648 bytes
2018-01-25 14:41:27,382 xcollector[2535] DEBUG: reading iostat.py, buffer now 1392 bytes
2018-01-25 14:41:27,383 xcollector[2535] DEBUG: reading dfstat.py, buffer now 2096 bytes
2018-01-25 14:41:29,386 xcollector[2535] DEBUG: reading procstats.py, buffer now 8447 bytes
2018-01-25 14:41:35,395 xcollector[2535] DEBUG: reading ifstat.py, buffer now 1056 bytes
2018-01-25 14:41:37,398 xcollector[2535] DEBUG: reading netstat.py, buffer now 2648 bytes
2018-01-25 14:41:44,408 xcollector[2535] DEBUG: reading procstats.py, buffer now 8447 bytes
2018-01-25 14:41:50,417 xcollector[2535] DEBUG: reading ifstat.py, buffer now 1056 bytes
2018-01-25 14:41:52,420 xcollector[2535] DEBUG: reading netstat.py, buffer now 2649 bytes
2018-01-25 14:41:59,429 xcollector[2535] DEBUG: reading procstats.py, buffer now 8447 bytes
2018-01-25 14:42:03,691 xcollector[2535] ERROR: Uncaught exception in SenderThread, going to exit
Traceback (most recent call last):
  File "/usr/local/xcollector/xcollector.py", line 547, in run
    self.send_data()
  File "/usr/local/xcollector/xcollector.py", line 691, in send_data
    return self.send_data_via_http()
  File "/usr/local/xcollector/xcollector.py", line 792, in send_data_via_http
    response = urllib2.urlopen(req, json.dumps(metrics))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)
BadStatusLine: ''
2018-01-25 14:42:03,721 xcollector[2535] INFO: shutting down children
2018-01-25 14:42:03,721 xcollector[2535] INFO: Waiting 5s for PID 2569 (procstats.py) to exit...
2018-01-25 14:42:04,722 xcollector[2535] INFO: Waiting 5s for PID 2570 (iostat.py) to exit...
2018-01-25 14:42:05,724 xcollector[2535] INFO: Waiting 5s for PID 2571 (dfstat.py) to exit...
2018-01-25 14:42:05,924 xcollector[2535] INFO: Waiting 5s for PID 2572 (ifstat.py) to exit...
2018-01-25 14:42:06,725 xcollector[2535] INFO: Waiting 5s for PID 2573 (netstat.py) to exit...
2018-01-25 14:42:06,926 xcollector[2535] DEBUG: Shutting down -- joining the reader thread.
2018-01-25 14:42:06,926 xcollector[2535] DEBUG: Shutting down -- joining the sender thread.
2018-01-25 14:42:07,726 xcollector[2535] INFO: exiting
```

**Comment by rshivane** [comment]
With #25 BadStatusLine and other HttpExceptions will be treated as re-tryable exceptions
